#!/bin/bash
set -euo pipefail

default() {
  test -z "$(find . -path ./vendor -prune -type f -o -name '*.go' -exec gofmt -d {} + | tee /dev/stderr)"
  go test -v $(go list ./... | grep -v '/vendor/')
  go vet $(go list ./... | grep -v '/vendor/')
}

with-cover() {
  rm -f cover*
  test -z "$(find . -path ./vendor -prune -type f -o -name '*.go' -exec gofmt -d {} + | tee /dev/stderr)"
  for d in $(go list ./... | grep -v '/vendor/'); do
    go test -v -coverprofile=profile.out -covermode=atomic $d
    if [ -f profile.out ]; then
      cat profile.out >> coverage.txt
      rm profile.out
    fi
  done

  if [ -f coverage.txt ]; then
    go tool cover -html=coverage.txt -o coverage.html
  fi

  go vet $(go list ./... | grep -v '/vendor/')
}

if [ -z ${1+x} ]; then
  default
else
  "$@"
fi
